### PR TITLE
Significant improvement in run times by addressing `SolutionDict#key()`

### PR DESCRIPTION
**Pull request by rolshoven**
When scaling to large population sizes (e.g. IPOP), a significant portion of the
wall-clock time for CMA-ES was taken by method `SolutionDict#key()`.
This commit addresses the problem by (i) switching to the built-in hash function,
(ii) skipping `np.ascontiguousarray` altogether, and (iii) replacing the call to
`self._hash` with a direct return statement, overall leading to a significant
reduction of run times.

I tested the difference in wall-clock speed using the following code snippet:

```python
import time
import numpy as np
import cma

budget_multiplier = 5e4
dimension = 40
fit_fn = cma.ff.schaffer

eval_budget = dimension * budget_multiplier + 1
evals_done = 0

def print_progress():
    global evals_done
    if evals_done % (eval_budget // 100) == 0:
        percentage = int(evals_done // (eval_budget // 100))
        print(f'{percentage}%', end='', flush=True)
    elif evals_done % (eval_budget // 400) == 0:
        print('.', end='', flush=True)

def problem(ind):
    global evals_done
    fit = fit_fn(ind)
    evals_done += 1
    print_progress()
    return fit

start = time.time()
while eval_budget - evals_done > 0:
    x0 = np.random.uniform(-4, 4, dimension)
    xopt, es = cma.fmin2(problem, x0, 2,
        {'maxfevals': eval_budget - evals_done, 'verbose':-9},
        restarts=9)
end = time.time()

seconds_elapsed = end - start
hours = int(seconds_elapsed // 3600)
minutes = int(seconds_elapsed % 3600 // 60)
seconds = int(seconds_elapsed % 3600 % 60)
formatted_time = f'{hours:02}h {minutes:02}m {seconds:02}s'

print(f'\n\nBudget exceeded! Optimization procedure took {formatted_time} ({seconds_elapsed:.0f} seconds).')
```

Without the changes, the evaluation budget was exceeded after 21 minutes and 42 seconds (1302 seconds in total). With the changes in place, it took only 9 minutes and 11 seconds (551 seconds in total), which is 2.36 times faster than before.

### CODE REVIEW

**Comment by rolshoven** [comment]
> Nice! I wonder whether is there a way to make this also work in Python 2.7?

Thank you for your reply! I was now able to understand why the `np.ascontiguousarray` was used in Python 2. I implemented a new version that works on my system with Python 2.7. It only applies the method `np.ascontiguousarray` when necessary, and it uses the built-in hash function to hash the array after temporarily setting it to read-only.

I tested it using this slightly modified script: 

```python
from __future__ import print_function

import time
import sys
import numpy as np
import cma

budget_multiplier = 5e4
dimension = 40
fit_fn = cma.ff.schaffer

eval_budget = dimension * budget_multiplier + 1
evals_done = 0

def print_progress():
    global evals_done
    if evals_done % (eval_budget // 100) == 0:
        percentage = int(evals_done // (eval_budget // 100))
        print(str(percentage) + '%', end='')
    elif evals_done % (eval_budget // 400) == 0:
        print('.', end='')
    sys.stdout.flush()

def problem(ind):
    global evals_done
    fit = fit_fn(ind)
    evals_done += 1
    print_progress()
    return fit

start = time.time()
while eval_budget - evals_done > 0:
    x0 = np.random.uniform(-4, 4, dimension)
    xopt, es = cma.fmin2(problem, x0, 2,
        {'maxfevals': eval_budget - evals_done, 'verbose':-9},
        restarts=9)
end = time.time()

seconds_elapsed = end - start
hours = int(seconds_elapsed // 3600)
minutes = int(seconds_elapsed % 3600 // 60)
seconds = int(seconds_elapsed % 3600 % 60)
formatted_time = str(hours) + 'h ' + str(minutes) + 'm ' + str(seconds) + 's'

print('\n\nBudget exceeded! Optimization procedure took ' + formatted_time + ' (' + str(seconds_elapsed) + ' seconds).')
```

The result: with the previous code it took 1h 2m 36s (3757 seconds in total) to execute the experiment. With the new code, the experiment was executed in 12m 21s (742 seconds in total), which is 5 times faster.

**Comment by nikohansen** [comment]
Why did you remove the fallback failure paths that return `self._hash(tuple(x))` etc.? I believe the previous code was also working when `isinstance(x, list)` is true, which I think is not the case anymore.

You might want to add
```python
        >>> assert d[[1,2,4]] == d[x]
        >>> d[2] = 3
        >>> assert d[2] == 3
```
to the doctest.

Does it make sense to expand
```python
if not x.flags['C_CONTIGUOUS']:
    x = np.ascontiguousarray(x)
```
to
```python
try:
    if not x.flags['C_CONTIGUOUS']:
        x = np.ascontiguousarray(x)
except:
    x = np.ascontiguousarray(x)
```

**Comment by rolshoven** [comment]
> > In Python 2, neither x.tobytes() nor np.ascontiguousarray(x).tobytes() will work
> 
> Are you sure?
> 
> ```python
> In [1]: sys.version_info
> Out[1]: sys.version_info(major=2, minor=7, micro=16, releaselevel='final', serial=0)
> 
> In [2]: x = np.array([1,2])
> 
> In [3]: np.ascontiguousarray(x).tobytes()
> Out[3]: '\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00'
> ```
> 
> works for me for some reason.

That's strange, maybe you are using a newer numpy version than me? My output is:

```python
In [1]: import numpy as np

In [2]: import sys

In [3]: sys.version_info
Out[3]: sys.version_info(major=2, minor=7, micro=16, releaselevel='final', serial=0)

In [4]: np.__version__
Out[4]: '1.8.0rc1'

In [5]: x = np.array([1,2])

In [6]: np.ascontiguousarray(x).tobytes()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-8d81dd5d3c7d> in <module>()
----> 1 np.ascontiguousarray(x).tobytes()

AttributeError: 'numpy.ndarray' object has no attribute 'tobytes'
```

> The code looks fine, though I am not fully comfortable with accessing the `data` attribute, as I can't find documentation on it.
> 
> EDIT: some spare doc: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.data.html EDIT: this describes the `data` attribute as optional https://numpy.org/devdocs/reference/arrays.interface.html#python-side and suggests that it's behavior is by no means guarantied.

In this case I think we should go with the `tobytes`, but I am concerned by the fact that it is not working on my laptop.

**Comment by nikohansen** [comment]
Excellent! Yes, I am in favor of squashing the commits. Just to be sure, do you still get the same performance gain?

**Pull request merged**
